name:                hal
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/hal#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

executables:
  step0_repl:
    source-dirs:      src
    main:             step0_repl.hs
